mysql:
  namespace: mysql

  image:
    name: mysql
    repository: mysql
    version: 8.0

  secrets:
    MYSQL_ROOT_PASSWORD: "1234"
    MYSQL_USER: "app_user"
    MYSQL_PASSWORD: "1234"
    MYSQL_DATABASE_NAME: "app_db"

  replicas: 2

  volumeClaimTemplates:
    resources:
      requests:
        storage: 2Gi

  resources:
    requests:
      cpu: 500m
      memory: 1Gi